### ISSUE TITLE
13- Place names/ business names/ proper nouns.

### ISSUE THREAD

**Issue by kyraneth** [LLBeirut/llbeirut#18]
we are currently using the tag "proper noun" in the features category of the transcription to specifcy personal names, however I was thinking that singling out toponyms could be useful as an encoding practice, as well as diferrentiating personal names and business names. However there is much overlap in these aforementionned two, and making that determination based of a single picture may be hard, and this is also the case with proper nouns and place names.

**Comment by djwrisley** [comment]
I think that the personal name and business name will be too difficult to disambiguate.  However, I agree the place name should be marked as such.
