### ISSUE TITLE
1001 multi-line structure

### ISSUE THREAD

**Issue by zj522** [LLBeirut/llbeirut#19]
=================================== 
Body:
  Paragraph1:
     "豆豆"
      Script: Asian
      Language: Chinese
      Feature: Proper Name, Equivalence
     "Dou Dou"
      Script: Latin
      Language: Chinese
      Feature: Proper Name, Equivalence
     "CHINESE RESTAURANT TAKE AWAY MENU"
      Script: Latin
      Language: English
      Feature: NULL
  Paragraph2:
     "Open Daily 12.00am - 11.30pm Delivery 12.00am - 11.30pm Private Parties Catered For 01 20 18 41 03 95 11 27"
      Script: Latin
      Language: English
      Feature: Western Number
     "Sioufi Street"
      Script: Latin
      Language: English
      Feature: Place Name
====================================
 
An issue arose when there are multiple lines with similar features such as numbers and I did not know whether to transcribe each line separately or merge everything together. David and I discussed this issue and temporarily decided to put everything into one paragraph (as seen in Paragraph 2). What are your opinions?

**Comment by kyraneth** [comment]
I think adding them all in one paragraph makes sense, especially that they are marked in the feature, however one interesting thing we might have to figure out is when multiple features need to be pointed out: For example, having a paragraph that is equivalent or a transliteration but also including numerals. Should we have the option to add multiple features, seperated by a comma, or, should we in these cases seperate the numerals so as to not have feature overlap?

**Comment by zj522** [comment]
David and I have discussed about this issue and updated the workflow. So whenever there's a new feature ( except numbers), we would start a new line.
