### ISSUE TITLE
Starting a new line upon finding a feature (except numbers)

### ISSUE THREAD

**Issue by zj522** [LLBeirut/llbeirut#21]
in the workflow, for the body we discussed starting a new line when you find a feature just as when a script or a language shifts.

Since numbers can be detected automatically, this does not apply to numbers.

**Comment by kyraneth** [comment]
They are, but there remains the issue of multiple features existing in the same transcription line, as I mentionned in issue 20, do you think we should have the ability to add multiple comma seperated features per transcribed line?

**Comment by djwrisley** [comment]
agreed.  Yes, multiple comma separated features are accepted.
